### ISSUE TITLE
ts-node error when running `start`

### ISSUE THREAD

**Issue by dan2468** [kamenminkov/vivaldi-bookmarks-dedupe#2]
The first `npm install` step works for me, but then `node -r ts-node/register --inspect app.ts` throws an error:
> […]\vivaldi-bookmarks-dedupe\node_modules\ts-node\src\index.ts:293
>    return new TSError(diagnosticText, diagnosticCodes)
>           ^
> TSError: ⨯ Unable to compile TypeScript:
> app.ts:4:8 - error TS2307: Cannot find module './paths'.
> 
> 4 import('./paths')
>          ~~~~~~~~~
> 
>     at createTSError ([…]\vivaldi-bookmarks-dedupe\node_modules\ts-node\src\index.ts:293:12)
>     at reportTSError ([…]\vivaldi-bookmarks-dedupe\node_modules\ts-node\src\index.ts:297:19)
>     at getOutput ([…]\vivaldi-bookmarks-dedupe\node_modules\ts-node\src\index.ts:399:34)
>     at Object.compile ([…]\vivaldi-bookmarks-dedupe\node_modules\ts-node\src\index.ts:457:32)
>     at Module.m._compile ([…]\vivaldi-bookmarks-dedupe\node_modules\ts-node\src\index.ts:530:43)
>     at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
>     at Object.require.extensions.<computed> [as .ts] ([…]\vivaldi-bookmarks-dedupe\node_modules\ts-> node\src\index.ts:533:12)
>     at Module.load (internal/modules/cjs/loader.js:1002:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)

Is this a versioning issue (some packages are a bit old now), or is there another development dependency that’s missing?

**Comment by kamenminkov** [comment]
Hey. Thanks for opening the issue and sorry for taking a bit too long to respond.

I guess the problem was that there was something wrong with the check whether `paths.ts` actually exists. For now the workaround would be to just include that file, but with an empty array in it - if it stays like this, it falls back to trying to find `Bookmarks` in the project's root. If you edit `paths.ts` to include your specific paths, it will use those.

Please pull the latest again and test.

**Comment by kamenminkov** [comment]
It should be fixed (see my previous comment), but if you stumble upon other issues, feel free to open another issue.
